name: CI

on:
  push:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run CI
        uses: Suban05/element-ci-action@v0.0.5
        with:
          config: |
            version: 7.0.5-57
            project_id: ${{ vars.PROJECT }}
            login: ${{ secrets.LOGIN }}
            password: ${{ secrets.PASSWORD }}
            branch: ${{ github.ref_name }}
            actions:
              -
                name: Tests
                title: Run tests
                method: post
                path: tests
